import {
  ArrowLeftRight,
  ArrowRightLeft,
  ArrowUpDown,
  Award,
  BadgeCheck,
  BadgePercent,
  BarChart3,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calculator,
  CandlestickChart,
  ClipboardCheck,
  ClipboardList,
  DollarSign,
  FileBadge,
  FileCheck,
  FileSearch,
  FileSignature,
  FileSpreadsheet,
  FileText,
  FileWarning,
  Gavel,
  Globe,
  Globe2,
  Handshake,
  HeartPulse,
  IdCard,
  Landmark,
  Lightbulb,
  LineChart,
  MessageSquare,
  Package,
  Plane,
  QrCode,
  Receipt,
  RefreshCw,
  Scale,
  ScrollText,
  Search,
  SearchCheck,
  Settings2,
  Shield,
  ShieldCheck,
  Shuffle,
  Stamp,
  Store,
  Target,
  TrendingDown,
  TrendingUp,
  Truck,
  Users,
  UtensilsCrossed,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { SERVICE_ICONS } from "@/lib/services-data";

const ICON_MAP: Record<string, LucideIcon> = {
  ArrowLeftRight,
  ArrowRightLeft,
  ArrowUpDown,
  Award,
  BadgeCheck,
  BadgePercent,
  BarChart3,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calculator,
  CandlestickChart,
  ClipboardCheck,
  ClipboardList,
  DollarSign,
  FileBadge,
  FileCheck,
  FileSearch,
  FileSignature,
  FileSpreadsheet,
  FileText,
  FileWarning,
  Gavel,
  Globe,
  Globe2,
  Handshake,
  HeartPulse,
  IdCard,
  Landmark,
  Lightbulb,
  LineChart,
  MessageSquare,
  Package,
  Plane,
  QrCode,
  Receipt,
  RefreshCw,
  Scale,
  ScrollText,
  Search,
  SearchCheck,
  Settings2,
  Shield,
  ShieldCheck,
  Shuffle,
  Stamp,
  Store,
  Target,
  TrendingDown,
  TrendingUp,
  Truck,
  Users,
  UtensilsCrossed,
  Zap,
};

export function getServiceIcon(slug: string): LucideIcon {
  const name = SERVICE_ICONS[slug];
  return ICON_MAP[name] ?? Briefcase;
}

export function ServiceIcon({ slug, className }: { slug: string; className?: string }) {
  const Icon = getServiceIcon(slug);
  return <Icon className={className} />;
}
