/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ResourcesFreeToolsRouteImport } from './routes/resources/free-tools'
import { Route as ResourcesComplianceCalendarRouteImport } from './routes/resources/compliance-calendar'

const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesFreeToolsRoute = ResourcesFreeToolsRouteImport.update({
  id: '/resources/free-tools',
  path: '/resources/free-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesComplianceCalendarRoute =
  ResourcesComplianceCalendarRouteImport.update({
    id: '/resources/compliance-calendar',
    path: '/resources/compliance-calendar',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/resources/compliance-calendar': typeof ResourcesComplianceCalendarRoute
  '/resources/free-tools': typeof ResourcesFreeToolsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/resources/compliance-calendar': typeof ResourcesComplianceCalendarRoute
  '/resources/free-tools': typeof ResourcesFreeToolsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/resources': typeof ResourcesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/resources/compliance-calendar': typeof ResourcesComplianceCalendarRoute
  '/resources/free-tools': typeof ResourcesFreeToolsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/industries'
    | '/insights'
    | '/resources/compliance-calendar'
    | '/resources/free-tools'
    | '/services/$slug'
    | '/resources/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/industries'
    | '/insights'
    | '/resources/compliance-calendar'
    | '/resources/free-tools'
    | '/services/$slug'
    | '/resources'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/industries'
    | '/insights'
    | '/resources/compliance-calendar'
    | '/resources/free-tools'
    | '/services/$slug'
    | '/resources/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  IndustriesRoute: typeof IndustriesRoute
  InsightsRoute: typeof InsightsRoute
  ResourcesComplianceCalendarRoute: typeof ResourcesComplianceCalendarRoute
  ResourcesFreeToolsRoute: typeof ResourcesFreeToolsRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/free-tools': {
      id: '/resources/free-tools'
      path: '/resources/free-tools'
      fullPath: '/resources/free-tools'
      preLoaderRoute: typeof ResourcesFreeToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/compliance-calendar': {
      id: '/resources/compliance-calendar'
      path: '/resources/compliance-calendar'
      fullPath: '/resources/compliance-calendar'
      preLoaderRoute: typeof ResourcesComplianceCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  IndustriesRoute: IndustriesRoute,
  InsightsRoute: InsightsRoute,
  ResourcesComplianceCalendarRoute: ResourcesComplianceCalendarRoute,
  ResourcesFreeToolsRoute: ResourcesFreeToolsRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
